version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MEETING_BAAS_API_KEY=${MEETING_BAAS_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_PORT=8000
      - WEBSOCKET_PORT=8001
      - DEBUG=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m websocket.handler
    ports:
      - "8001:8001"
    environment:
      - MEETING_BAAS_API_KEY=${MEETING_BAAS_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_PORT=8000
      - WEBSOCKET_PORT=8001
      - DEBUG=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
